export const data = {
  navbar: [
    {
      title: "CURRENT ISSUE",
      href: "/current-issue",
      subMenu: [],
    },

    {
      title: "ARCHIVES",
      href: "/archives",
      subMenu: [
        {
          title: "CURRENT ISSUE",
          href: "/current-issue",
          query: "current-issue",
          subLinks: [],
        },
        {
          title: "PAST ISSUE",
          href: "/past-issue",
          query: "past-issue",
          subLinks: [],
        },
        {
          title: "SPECIAL ISSUE",
          href: "/special-issue",
          query: "special-issue",
          subLinks: [],
        },
      ],
    },
    {
      title: "FOR AUTHOR",
      href: "/author",
      subMenu: [
        {
          title: "CALL FOR PAPER",
          href: "/call-for-paper",
          query: "call-for-paper",
          subLinks: [],
        },
        {
          title: "PUBLICATION GUIDE",
          href: "/publication-guide",
          query: "publication-guide",
          subLinks: [],
        },
        {
          title: "PROCESSING CHARGE",
          href: "/processing-charge",
          query: "processing-charge",
          subLinks: [],
        },
        {
          title: "PAY NOW",
          href: "/pay-now",
          query: "pay-now",
          subLinks: [],
        },
        {
          title: "SAMPLE PAPER FORMAT",
          href: "/sample-paper-format",
          query: "sample-paper-format",
          subLinks: [],
        },
        {
          title: "COPYRIGHT FORM",
          href: "/copyright-form",
          query: "copyright-form",
          subLinks: [],
        },
        {
          title: "INDEXING & ABSTRACTING",
          href: "/indexing-and-abstracting",
          query: "indexing-and-abstracting",
          subLinks: [],
        },
        {
          title: "ETHICS POLICY",
          href: "/ethics-policy",
          query: "ethics-policy",
          subLinks: [],
        },
      ],
    },

    {
      title: "About Us",
      href: "/about",
      subMenu: [],
    },
    {
      title: "FAQ",
      href: "/faq",
      subMenu: [],
    },
  ],

  researchTopics: [
    "Biochemistry",
    "Biological techniques",
    "Biophysics",
    "Biotechnology",
    "Cancer",
    "Cell biology",
    "Chemical biology",
    "Computational biology and bioinformatics",
    "Developmental biology",
    "Drug discovery",
    "Ecology",
    "Evolution",
    "Genetics",
    "Immunology",
    "Microbiology",
    "Molecular biology",
    "Neuroscience",
    "Physiology",
    "Plant sciences",
    "Psychology",
    "Stem cells",
    "Structural biology",
    "Systems biology",
    "Zoology",
    "Business and management",
    "Economics",
    "Finance",
    "Information systems and information technology",
    "Operational research",
    "Biogeochemistry",
    "Climate sciences",
    "Ecology",
    "Environmental sciences",
    "Environmental social sciences",
    "Hydrology",
    "Limnology",
    "Natural hazards",
    "Ocean sciences",
    "Planetary science",
    "Solid Earth sciences",
    "Space physics",
    "Anatomy",
    "Biomarkers",
    "Cardiology",
    "Diseases",
    "Endocrinology",
    "Gastroenterology",
    "Health care",
    "Health occupations",
    "Medical research",
    "Molecular medicine",
    "Nephrology",
    "Neurology",
    "Oncology",
    "Pathogenesis",
    "Rheumatology",
    "Risk factors",
    "Signs and symptoms",
    "Urology",
    "Complex networks",
    "Cultural and media studies",
    "Health humanities",
    "History",
    "Language and linguistics",
    "Literature",
    "Medical humanities",
    "Philosophy",
    "Religion",
    "Theatre and performance studies",
    "Astronomy and planetary science",
    "Chemistry",
    "Energy science and technology",
    "Engineering",
    "Materials science",
    "Mathematics and computing",
    "Nanoscience and technology",
    "Optics and photonics",
    "Physics",
    "Agriculture",
    "Business and industry",
    "Developing world",
    "Energy and society",
    "Forestry",
    "Geography",
    "Scientific community",
    "Social sciences",
    "Water resources",
    "Anthropology",
    "Business and management",
    "Complex networks",
    "Criminology",
    "Cultural and media studies",
    "Development studies",
    "Economics",
    "Education",
    "Environmental studies",
    "Finance",
    "Geography",
    "History",
    "Language and linguistics",
    "Politics and international relations",
    "Psychology",
    "Science, technology and society",
    "Social policy",
    "Sociology",
  ],
  issues: [
    "Issue 1",
    "Issue 2",
    "Issue 3",
    "Issue 4",
    "Issue 5",
    "Issue 6",
    "Issue 7",
    "Issue 8",
    "Issue 9",
    "Issue 10",
    "Issue 11",
    "Issue 12",
  ],
  volumes: [
    "Volume 1",
    "Volume 2",
    "Volume 3",
    "Volume 4",
    "Volume 5",
    "Volume 6",
  ],
};
