import { title } from "process";
import images from "./images";

export const data = {
  navbar: [
    {
      title: "CURRENT ISSUE",
      href: "/current-issue",
      subMenu: [],
    },

    {
      title: "ARCHIVES",
      href: "/archives",
      subMenu: [
        {
          title: "CURRENT ISSUE",
          href: "/current-issue",
          query: "current-issue",
          subLinks: [],
        },
        {
          title: "PAST ISSUE",
          href: "/past-issue",
          query: "past-issue",
          subLinks: [],
        },
        {
          title: "SPECIAL ISSUE",
          href: "/special-issue",
          query: "special-issue",
          subLinks: [],
        },
      ],
    },
    {
      title: "FOR AUTHOR",
      href: "/author",
      subMenu: [
        {
          title: "CALL FOR PAPER",
          href: "/call-for-paper",
          query: "call-for-paper",
          subLinks: [],
        },
        {
          title: "PUBLICATION GUIDE",
          href: "/publication-guide",
          query: "publication-guide",
          subLinks: [],
        },
        {
          title: "PROCESSING CHARGE",
          href: "/processing-charge",
          query: "processing-charge",
          subLinks: [],
        },
        {
          title: "PAY NOW",
          href: "/pay-now",
          query: "pay-now",
          subLinks: [],
        },
        {
          title: "SAMPLE PAPER FORMAT",
          href: "/sample-paper-format",
          query: "sample-paper-format",
          subLinks: [],
        },
        {
          title: "COPYRIGHT FORM",
          href: "/copyright-form",
          query: "copyright-form",
          subLinks: [],
        },
        {
          title: "INDEXING & ABSTRACTING",
          href: "/indexing-and-abstracting",
          query: "indexing-and-abstracting",
          subLinks: [],
        },
        {
          title: "ETHICS POLICY",
          href: "/ethics-policy",
          query: "ethics-policy",
          subLinks: [],
        },
      ],
    },

    {
      title: "About Us",
      href: "/about",
      subMenu: [],
    },
    {
      title: "FAQ",
      href: "/faq",
      subMenu: [],
    },
  ],

  researchTopics: [
    "Biochemistry",
    "Biological techniques",
    "Biophysics",
    "Biotechnology",
    "Cancer",
    "Cell biology",
    "Chemical biology",
    "Computational biology and bioinformatics",
    "Developmental biology",
    "Drug discovery",
    "Ecology",
    "Evolution",
    "Genetics",
    "Immunology",
    "Microbiology",
    "Molecular biology",
    "Neuroscience",
    "Physiology",
    "Plant sciences",
    "Psychology",
    "Stem cells",
    "Structural biology",
    "Systems biology",
    "Zoology",
    "Business and management",
    "Economics",
    "Finance",
    "Information systems and information technology",
    "Operational research",
    "Biogeochemistry",
    "Climate sciences",
    "Ecology",
    "Environmental sciences",
    "Environmental social sciences",
    "Hydrology",
    "Limnology",
    "Natural hazards",
    "Ocean sciences",
    "Planetary science",
    "Solid Earth sciences",
    "Space physics",
    "Anatomy",
    "Biomarkers",
    "Cardiology",
    "Diseases",
    "Endocrinology",
    "Gastroenterology",
    "Health care",
    "Health occupations",
    "Medical research",
    "Molecular medicine",
    "Nephrology",
    "Neurology",
    "Oncology",
    "Pathogenesis",
    "Rheumatology",
    "Risk factors",
    "Signs and symptoms",
    "Urology",
    "Complex networks",
    "Cultural and media studies",
    "Health humanities",
    "History",
    "Language and linguistics",
    "Literature",
    "Medical humanities",
    "Philosophy",
    "Religion",
    "Theatre and performance studies",
    "Astronomy and planetary science",
    "Chemistry",
    "Energy science and technology",
    "Engineering",
    "Materials science",
    "Mathematics and computing",
    "Nanoscience and technology",
    "Optics and photonics",
    "Physics",
    "Agriculture",
    "Business and industry",
    "Developing world",
    "Energy and society",
    "Forestry",
    "Geography",
    "Scientific community",
    "Social sciences",
    "Water resources",
    "Anthropology",
    "Business and management",
    "Complex networks",
    "Criminology",
    "Cultural and media studies",
    "Development studies",
    "Economics",
    "Education",
    "Environmental studies",
    "Finance",
    "Geography",
    "History",
    "Language and linguistics",
    "Politics and international relations",
    "Psychology",
    "Science, technology and society",
    "Social policy",
    "Sociology",
  ],

  issues: [
    "Issue 1",
    "Issue 2",
    "Issue 3",
    "Issue 4",
    "Issue 5",
    "Issue 6",
    "Issue 7",
    "Issue 8",
    "Issue 9",
    "Issue 10",
    "Issue 11",
    "Issue 12",
  ],

  volumes: [
    "Volume 1",
    "Volume 2",
    "Volume 3",
    "Volume 4",
    "Volume 5",
    "Volume 6",
  ],

  services: [
    {
      icon: images.service1,
      title: "Indexing the world’s repositories",
      description: "We serve the global network of repositories and journals",
    },
    {
      icon: images.service2,
      title: "Comprehensive data coverage",
      description:
        "We provide both metadata and full text access to our comprehensive collection through our APIs and Datasets",
    },
    {
      icon: images.service3,
      title: "Powerful services",
      description:
        "We create powerful services for researchers, universities, and industry",
    },
    {
      icon: images.service4,
      title: "Cutting-edge solutions",
      description:
        "We research and develop innovative data-driven and AI solutions",
    },
  ],

  coreSerctions: [
    {
      icon: images.core1,
      title: "Become a data provider",
      href: "/data-provider",
    },
    {
      icon: images.core2,
      title: "become a member",
      href: "/register",
    },
    {
      icon: images.core3,
      title: "explore our services",
      href: "/services",
    },
  ],

  serveSections: [
    {
      title: "Companies",
      description:
        "Enabling others to create new tools and innovate using a global comprehensive collection of research papers.",
      quote:
        "Our partnership with CORE will provide Turnitin with vast amounts of metadata and full texts that we can utilise in our plagiarism detection software.",
      partner: "Gareth Malcolm, Content Partner Manager at Turnitin",
    },
    {
      title: "Academic institutions",
      description:
        "Making research more discoverable, improving metadata quality, helping to meet and monitor open access compliance.",
      quote:
        "CORE’s role in providing a unified search of repository content is a great tool for the researcher and extends the reach of the locally held content in our institutional repository, Open Research Online",
      partner: "Nicola Dowson, Library Services Manager at Open University",
    },
    {
      title: "Researchers & general public",
      description:
        "Tools to find, discover and explore the wealth of open access research. Free for everyone, forever.",
      quote:
        "With millions of research papers available across thousands of different systems, CORE provides an invaluable service helping researchers to save time and effort. CORE’s mission to make all this content available for text and data mining is critical for future avenues of research, and a major part of advancing open science.",
      partner:
        "Jon Tennant, Rogue Paleontologist and Founder of the Open Science MOOC",
    },
    {
      title: "Funders",
      description:
        "Helping funders to analyse, audit and monitor open research and accelerate towards open science.",
      quote:
        "Aggregation plays an increasingly essential role in maximising the long-term benefits of open access, helping to turn the promise of a 'research commons' into a reality. The aggregation services that CORE provides therefore make a very valuable contribution to the evolving open access environment in the UK.",
      partner: "Ben Johnson, Research Policy Adviser at Research England",
    },
  ],

  recents: [
    {
      title: "ACM Transactions on Internet of Things",
      issue: 1,
      volume: 56,
      date: "01-01-2024",
    },
    {
      title: "ACM Transactions on Internet of Things",
      issue: 2,
      volume: 57,
      date: "02-05-2023",
    },
    {
      title: "ACM Transactions on Internet of Things",
      issue: 5,
      volume: 58,
      date: "01-01-2024",
    },
    {
      title: "ACM Transactions on Internet of Things",
      issue: 5,
      volume: 58,
      date: "01-01-2024",
    },
    {
      title: "ACM Transactions on Internet of Things",
      issue: 1,
      volume: 56,
      date: "01-01-2024",
    },
    {
      title: "ACM Transactions on Internet of Things",
      issue: 2,
      volume: 57,
      date: "02-05-2023",
    },
    {
      title: "ACM Transactions on Internet of Things",
      issue: 5,
      volume: 58,
      date: "01-01-2024",
    },
    {
      title: "ACM Transactions on Internet of Things",
      issue: 5,
      volume: 58,
      date: "01-01-2024",
    },
    {
      title: "ACM Transactions on Internet of Things",
      issue: 1,
      volume: 56,
      date: "01-01-2024",
    },
    {
      title: "ACM Transactions on Internet of Things",
      issue: 2,
      volume: 57,
      date: "02-05-2023",
    },
    {
      title: "ACM Transactions on Internet of Things",
      issue: 5,
      volume: 58,
      date: "01-01-2024",
    },
    {
      title: "ACM Transactions on Internet of Things",
      issue: 5,
      volume: 58,
      date: "01-01-2024",
    },
    {
      title: "ACM Transactions on Internet of Things",
      issue: 1,
      volume: 56,
      date: "01-01-2024",
    },
    {
      title: "ACM Transactions on Internet of Things",
      issue: 2,
      volume: 57,
      date: "02-05-2023",
    },
    {
      title: "ACM Transactions on Internet of Things",
      issue: 5,
      volume: 58,
      date: "01-01-2024",
    },
    {
      title: "ACM Transactions on Internet of Things",
      issue: 5,
      volume: 58,
      date: "01-01-2024",
    },
  ],
};
